### ISSUE TITLE
In map view, if no states are checked check all

### ISSUE THREAD

**Issue by tguar** [victorh3/residency-ui#1]
As as user if I unselect all states in map view I want to show all states.

Currently if I unselect all then it will show all states (intended behavior) but all states are unchecked.

![one state checked, showing one state](https://user-images.githubusercontent.com/6622466/80895579-60330f80-8c9b-11ea-8aaa-fc836e5f2589.png)
one state checked, showing one state

![no states checked, showing all states](https://user-images.githubusercontent.com/6622466/80895581-675a1d80-8c9b-11ea-9136-2a52c9f17670.png)
no states checked, showing all states

![all states checked, showing all states 2](https://user-images.githubusercontent.com/6622466/80895643-e64f5600-8c9b-11ea-97dd-c129ecdc5385.png)
no states checked should show all states and check all states

**Comment by victorh3** [comment]
I like the idea, but rather than managing all checkboxes, ill add a "select all" to the top that will be checked when no states are selected, and unselecting it would return your last filters.

**Comment by victorh3** [comment]
Feature has been implemented and deployed.
